#ifndef KPPHARDWARE_GLOBAL_H
#define KPPHARDWARE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(KPPHARDWARE_LIBRARY)
#  define KPPHARDWARESHARED_EXPORT Q_DECL_EXPORT
#else
#  define KPPHARDWARESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // KPPHARDWARE_GLOBAL_H
